// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMUxdaOwRoSaPeHZycb1s5UJcg_kyvh9w',
    appId: '1:748795669195:web:01196e29c3e0b2c3e7494e',
    messagingSenderId: '748795669195',
    projectId: 'vote-ready-93a5f',
    authDomain: 'vote-ready-93a5f.firebaseapp.com',
    storageBucket: 'vote-ready-93a5f.appspot.com',
    measurementId: 'G-X84CHP6PB4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMZ3Ya0hcxKeObCR9HSNYEvV-Je-zYekw',
    appId: '1:748795669195:android:ec2e80d42063cb4de7494e',
    messagingSenderId: '748795669195',
    projectId: 'vote-ready-93a5f',
    storageBucket: 'vote-ready-93a5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAofSLoM8r64-QBbms3uHx77KkjttcYq8w',
    appId: '1:748795669195:ios:fdc64617cd636dbae7494e',
    messagingSenderId: '748795669195',
    projectId: 'vote-ready-93a5f',
    storageBucket: 'vote-ready-93a5f.appspot.com',
    androidClientId: '748795669195-vn8tqt90b6o4ov6rfmqlmv6vr1rd6nr5.apps.googleusercontent.com',
    iosClientId: '748795669195-ntacoupsr8ohjg8394v131dr8qfv40hj.apps.googleusercontent.com',
    iosBundleId: 'com.example.voteReady',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAofSLoM8r64-QBbms3uHx77KkjttcYq8w',
    appId: '1:748795669195:ios:94bb465449f99343e7494e',
    messagingSenderId: '748795669195',
    projectId: 'vote-ready-93a5f',
    storageBucket: 'vote-ready-93a5f.appspot.com',
    androidClientId: '748795669195-vn8tqt90b6o4ov6rfmqlmv6vr1rd6nr5.apps.googleusercontent.com',
    iosClientId: '748795669195-m7mjnguq5jmqqm5cr7ijb2grt5ucsiot.apps.googleusercontent.com',
    iosBundleId: 'com.example.voteReady.RunnerTests',
  );
}
